### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yohei-ota** [yohei-ota/furima-36556#20]
# URL
フリマアプリのURL
https://furima-36556.herokuapp.com/

Basic認証のIDとパスワード
ID: furima
パスワード:8888

出品者用のメールアドレスとパスワード
アドレス:aaa@aaa
パスワード:hhhhhh1

購入者用のメールアドレスとパスワード
アドレスbbb@bbb
パスワード:hhhhhh1

**Comment by takumi0530** [comment]
@yohei-ota さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **商品出品時に登録した情報（商品名・商品画像・販売価格・配送料負担・商品説明・出品者名・カテゴリー・商品の状態・発送元の地域・発送日の目安）が、見本アプリと同様の形で出力されること**
- [x] **商品出品時に登録した情報のうち、「商品名・商品画像・価格・配送料の負担」の4つの情報が、見本アプリと同様の形で表示されること**
販売価格が表示されておりませんでした。
<img width="682" alt="スクリーンショット 2021-08-25 18 12 23" src="https://user-images.githubusercontent.com/76197191/130763347-b8a4c245-b897-43d7-b674-94cb0e8bd2d3.png">
<img width="530" alt="スクリーンショット 2021-08-25 18 14 20" src="https://user-images.githubusercontent.com/76197191/130763572-3469adf3-ff5d-4da1-9b00-d466d2a8e8b1.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yohei-ota** [comment]
修正いたしました。
ご確認よろしくお願いします。

**Comment by snkw-works** [comment]
@yohei-ota さん、お待たせいたしました。フリマアプリ達成要件分の開発お疲れ様でした！
修正が確認でき、問題なく正常に動作することが確認できました！ **LGTM**です！　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

#### ＜今後の学習例＞
```
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
```
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。

また、以下提出物に関するリマインドです。

#### ＜提出物＞
```
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
```
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

#### ＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/6852

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/130884123-3c528bb8-d61b-41a7-8bc1-144ac9b47874.png)
